name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Build and deploy to GitHub Pages
        run: |
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          npm install  # Or any build commands you need
          npm run build  # Replace with your build script
          git checkout gh-pages
          git rm -rf .
          mv /dist/* .
          git add .
          git commit -m "Deploy to GitHub Pages"
          git push origin gh-pages
